name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
    - main
    - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Copy the plugin files to the plugin check folder, excluding the files on .distignore.
      run: rsync -rc --exclude-from="$GITHUB_WORKSPACE/.distignore" "$GITHUB_WORKSPACE/"  --delete --delete-excluded

    - name: Run plugin check
      uses: swissspidy/wp-plugin-check-action@v1
      with:
        exclude-directories: '.github'
   

